### ISSUE TITLE
Docker2singularity broken for selected images

### ISSUE THREAD

**Issue by gnguy** [singularityware/docker2singularity#22]
Hi,

After pulling the most recent docker2singularity version, it now breaks when trying to convert various images. Could this be related to the changes made in the following PR? https://github.com/singularityware/docker2singularity/commit/04c465d38d58fad48d0a4a4b46515356cb81fb88

See below for error messages. 

> docker run -v /var/run/docker.sock:/var/run/docker.sock -v ~/Desktop:/output --privileged -t --rm singularityware/docker2singularity continuumio/miniconda
> Size: 655 MB for the singularity container
> (1/9) Creating an empty image...
> Creating a sparse image with a maximum size of 655MiB...
> Using given image size of 655
> Formatting image (/sbin/mkfs.ext3)
> Done. Image can be found at: /tmp/continuumio_miniconda-2017-06-04-656a1fe1d99e.img
> (2/9) Importing filesystem...
> (3/9) Bootstrapping...
> (4/9) Adding run script...
> (5/9) Setting ENV variables...
> Singularity: sexec (U=0,P=146)> Command=exec, Container=/tmp/continuumio_miniconda-2017-06-04-656a1fe1d99e.img, CWD=/, Arg1=/bin/sh
> (6/9) Adding mount points...
> Singularity: sexec (U=0,P=152)> Command=exec, Container=/tmp/continuumio_miniconda-2017-06-04-656a1fe1d99e.img, CWD=/, Arg1=/bin/sh
> (7/9) Fixing permissions...
> Singularity: sexec (U=0,P=158)> Command=exec, Container=/tmp/continuumio_miniconda-2017-06-04-656a1fe1d99e.img, CWD=/, Arg1=/bin/sh
> We're running on BusyBox/Buildroot
> Singularity: sexec (U=0,P=199)> Command=exec, Container=/tmp/continuumio_miniconda-2017-06-04-656a1fe1d99e.img, CWD=/, Arg1=/bin/sh
> find: `/proc/2/task/2/fd/11': No such file or directory
> find: `/proc/2/task/2/fd/11': No such file or directory
> find: `/proc/2/task/2/fdinfo/11': No such file or directory
> find: `/proc/2/task/2/fdinfo/11': No such file or directory
> find: `/proc/2/fd/11': No such file or directory
> find: `/proc/2/fd/11': No such file or directory
> find: `/proc/2/fdinfo/11': No such file or directory
> find: `/proc/2/fdinfo/11': No such file or directory

Docker info: 

> Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64

**Comment by gnguy** [comment]
To add additional information, the version of docker2singularity that I was using previously (pulled 4 months ago), works fine.

**Comment by chrisfilo** [comment]
Interesting. I can confirm those warnings occur. Not sure how this change could produce this effect. Maybe the image you are converting changed?

Does the created singularity image work nonetheless?

**Comment by gnguy** [comment]
Unfortunately, the singularity image does not get created after it hits the find-related errors, and the errors happen when trying to convert different, unrelated images. Some images (nginx, rocker/rstudio, debian:latest) work, while others (continuumio/miniconda, debian:8.5, redis:latest) do not.

**Comment by spiropan** [comment]
Hello,
I'm getting the exact same error when trying to convert bids/freesurfer to singularity image using docker versions 1.12 and 1.13 on Mac OS X and Ubuntu 14.04 respectively (terminal output below). Is there any workaround that you might recommend until the issue is fixed? 
Thank you

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /Users/Spiro/singularity_images:/output --privileged -t --rm singularityware/docker2singularity:1.12 bids/freesurfer
Unable to find image 'singularityware/docker2singularity:1.12' locally
1.12: Pulling from singularityware/docker2singularity

b7f33cc0b48e: Pull complete 
1438997aafae: Pull complete 
4096f0da5ead: Pull complete 
db8d140dbabd: Pull complete 
...
Digest: sha256:ad0ab5a03f494c0fd164f640da8b16b2aaef4c4c07e521720ad0e4c64d4a4887
Status: Downloaded newer image for singularityware/docker2singularity:1.12
Unable to find image 'bids/freesurfer:latest' locally
latest: Pulling from bids/freesurfer
f3ead5e8856b: Pulling fs layer
...
b03c617adff5: Waiting
adc158cff9ba: Pull complete
6a507d194ee1: Pull complete
Digest: sha256:b92eac6d2687baa8f7b2d048dffb996e1363ed7f6eb877da6db507ee7e5cdae4
Status: Downloaded newer image for bids/freesurfer:latest
Size: 9609 MB for the singularity container
(1/9) Creating an empty image...
Creating a sparse image with a maximum size of 9609MiB...
Using given image size of 9609
Formatting image (/sbin/mkfs.ext3)
Done. Image can be found at: /tmp/bids_freesurfer-2017-05-28-0b0cf2bee625.img
(2/9) Importing filesystem...
(3/9) Bootstrapping...
(4/9) Adding run script...
(5/9) Setting ENV variables...
Singularity: sexec (U=0,P=120)> Command=exec, Container=/tmp/bids_freesurfer-2017-05-28-0b0cf2bee625.img, CWD=/, Arg1=/bin/sh
(6/9) Adding mount points...
Singularity: sexec (U=0,P=126)> Command=exec, Container=/tmp/bids_freesurfer-2017-05-28-0b0cf2bee625.img, CWD=/, Arg1=/bin/sh
(7/9) Fixing permissions...
Singularity: sexec (U=0,P=132)> Command=exec, Container=/tmp/bids_freesurfer-2017-05-28-0b0cf2bee625.img, CWD=/, Arg1=/bin/sh
We're running on BusyBox/Buildroot
Singularity: sexec (U=0,P=175)> Command=exec, Container=/tmp/bids_freesurfer-2017-05-28-0b0cf2bee625.img, CWD=/, Arg1=/bin/sh
find: `/proc/2/task/2/fd/11': No such file or directory
find: `/proc/2/task/2/fd/11': No such file or directory
find: `/proc/2/task/2/fdinfo/11': No such file or directory
find: `/proc/2/task/2/fdinfo/11': No such file or directory
find: `/proc/2/fd/11': No such file or directory
find: `/proc/2/fd/11': No such file or directory
find: `/proc/2/fdinfo/11': No such file or directory
find: `/proc/2/fdinfo/11': No such file or directory

**Comment by chrisfilo** [comment]
This should be fixed now - please try pulling a new version of `singularityware/docker2singularity`.

**Comment by gnguy** [comment]
After pulling, it works great. Thanks for the fix!

**Comment by spiropan** [comment]
Worked for me too, thank you!
