### ISSUE TITLE
output destination

### ISSUE THREAD

**Issue by rwtaylor** [singularityware/docker2singularity#8]
The documentation at "http://singularity.lbl.gov/docs-docker" indicates that docker2singularity will produce a singularity image in the current directory

> To produce a Singularity image of “ubuntu:latest” in the present working directory.

But docker2singularity outputs to /output/

**Comment by seantma** [comment]
I would like to +1 on this.

Initially I thought I could point directly to the directory where the image should be placed, such as 
`-v /home/vagrant/temp` (from the quoted code below). 

But somehow the output `.img` couldn't be found anywhere. After multiple trials (and hair pulling), it seems you **MUST** have the `:/output` at the end of the placement directory in order to output the image:
`-v /home/vagrant/temp:/output`

Adding more confusion is the converted `.img` file is not placed in the `/output` directory, but rather in the `/home/vagrant/temp` directory instead. 

> $ docker run -v /var/run/docker.sock:/var/run/docker.sock \
>     -v D:\host\path\where\to\ouptut\singularity\image:/output \
>     --privileged -t --rm singularityware/docker2singularity \
>     ubuntu:14.04

**Comment by vsoch** [comment]
hey @seantma is this still an issue for you? Have you tried singularity (native) without docker2singularity to produce your image?

```
singularity pull ubuntu.simg docker://ubuntu:14.04
```

**Comment by vsoch** [comment]
hey @seantma, the folder /output is inside the Docker image, and so you would get your custom location (on the host) by binding to it. Eg, when running the container, let's say I have `/tmp/test` on my host:

```
-v /tmp/test:/output
```

I bind to output. Note that for the recent PR for version 2.5.1 we are adding the ability to name the container (within this output directory). This should give you full control over the name. I'm closing the issue as it's over a year old but please open a new one with the latest branch if you have trouble. Thanks!
